### ISSUE TITLE
Left margin is twice as wide as right margin.

### ISSUE THREAD

**Issue by fbie** [anler/centered-window-mode#15]
Hi, I am a huge fan of `centered-window-mode`, but the last update to `20170402.1012` broke my setup. The margin on the left is twice as wide as on the right. I quickly looked at the code, but I could not figure out what might be going wrong. Any pointers?

![screenshot from 2017-04-06 17-55-56](https://cloud.githubusercontent.com/assets/2356547/24748476/5c982702-1af2-11e7-813f-cfd26fefdbee.png)

I run Emacs as a daemon and use `use-package` in my init file.

**Comment by anler** [comment]
Hi @fbie sorry breaking your setup 😞  I believe I did that on purpose because usually one is more interested in the code at the left (so its better if it's a bit more to the center) and pay less attention to the end of the lines in the right. But if it's not ok for you I'm gonna change it to be at least configurable or something 😃

**Comment by fbie** [comment]
Configurable would be nice! I write a lot of Latex in Emacs and usually my lines get pretty long. I can see and try whether I can implement it myself :)

**Comment by anler** [comment]
@fbie ask me if you need help
